### ISSUE TITLE
BUG: Github-Dark compatibility: anchor color too dark

### ISSUE THREAD

**Issue by enricoreich** [ovity/octotree#668]
### Description
If you use Github-Dark usercss, the anchor color for jstree-anchor is too dark!

because of:
```css
.octotree-sidebar.octotree-github-sidebar .octotree-views .octotree-tree-view .jstree-anchor {
	color: #0f2e47 !important;
    ...
}
```

### Environment (if bug)

* Octotree version: 3.0.1 (non-PRO)
* Browser & version: Firefox 66.0.3
* OS & version: Windows 10
* Screenshot:

![jstree-anchor-color](https://user-images.githubusercontent.com/316637/56147950-90811080-5fa9-11e9-9904-198dfbbff19d.png)
