### ISSUE TITLE
Octotree overlay file when I create new PR

### ISSUE THREAD

**Issue by hong4rc** [ovity/octotree#707]
![image](https://user-images.githubusercontent.com/19208123/56845338-d6af6b80-68e9-11e9-8434-fd3ae6bc5eae.png)

**Comment by nphi** [comment]
@Hongarc,

Thanks for reporting the issue. It seems I'm missing something so that I couldn't reproduce the issue. Could you give more information to reproduce it ? ( your screen resolution, Octotree version, your OS ). It would ore helpful if you could provide a GIF. I really appreciate your cooperation !

Octotree 3.0.7 looks good on my screen in the create new PR page
![Screen Shot 2019-04-27 at 12 53 35 PM](https://user-images.githubusercontent.com/8633840/56845474-e9c33b00-68eb-11e9-8545-47e6fedb0ee5.png)

**Comment by Hongarc** [comment]
- Octotree 3.0.7
- Window 10 x64
- Chrome 74.0.3729.108 (Official Build) (64-bit)
I will add gif later

Thank you

**Comment by nphi** [comment]
Good news. I'm able to reproduce the bug. I will try to fix it ASAP. Thanks for your help.

**Comment by Mottie** [comment]
I had a user ask me to make the [Octotree side bar not overlap](https://github.com/Mottie/GitHub-userscripts/issues/85) the page content, especially when a GitHub wide style is applied. Do you think there is any way to get this incorporated into Octotree?

```css
:root {
  --octotree-width: 350px; /* dynamically updated value */
}
```

```css
html body > div:not(.js-header-wrapper),
.Header {
	transform: translate3d(0px, 0px, 0px);
	transition: transform 0.2s ease 0.1s;
}
html.octotree-show body > div:not(.js-header-wrapper),
html.octotree-show .Header:not([style]) {
	transform: translate3d(var(--octotree-width), 0px, 0px);
}
```
