### ISSUE TITLE
Repo title with tall letters are cut off

### ISSUE THREAD

**Issue by joedf** [ovity/octotree#741]
### Description
The `overflow: hidden;` rule used here causes the header to be cut off with "tall" letters. For example, see https://github.com/aircrack-ng/aircrack-ng The g's are cut-off.
```css
.octotree-sidebar.octotree-github-sidebar .octotree-views .octotree-tree-view .octotree-view-header .octotree-header-repo, .octotree-sidebar.octotree-github-sidebar .octotree-views .octotree-tree-view .octotree-view-header .octotree-header-branch {
    width: 100%;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

### Environment (if bug)

* Octotree version: 3.0.8
* Browser & version: Firefox x64 67.0.4
* OS & version: Win10 Pro x64 Build 1809
* Screenshot, if any (drag an image here)
![firefox_2019-07-12_14-21-50-edit](https://user-images.githubusercontent.com/3848219/61150082-8d19fa00-a4b0-11e9-9147-56b844d44e6b.png)
