### ISSUE TITLE
Dark Themes - Colourise Pull Request List Icons

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#959]
### Description
When viewing the Pull Requests GitHub page (and PR lists page), the mini Failed, Pass, and even the Merge icons are de-colourised for each Pull Request listed when using any of the Dark themes (eg, _Monokai_). 

It makes it hard to distinguish between Pull Requests which have failed, or passed the automated build checks (eg, Jenkins tests) integrated into the repositories (if applicable).

A suggestion is to at least maintain the same colour to the icons that is visible when no colour theme is set (eg, red for Failed, Green for Passed, and also Green for the Merge icon to the left of the Pull Request title)

### Environment (if bug)

* **Octotree version**: 5.0.0
* **Browser & version**: 83.0.4103.61
* **OS & version**: OS X 10.15.5 (Catalina)
* **Screenshot**:
![Octotree-Monokai-Color-Theme](https://user-images.githubusercontent.com/7581546/83609014-90f5b580-a575-11ea-8567-c358998ac395.png)

![Screenshot 2020-06-03 at 15 07 38](https://user-images.githubusercontent.com/7581546/83647388-bce05d80-a5ac-11ea-8f02-8dba15a7f8b8.png)

* **Console error log below this line**: N/A

**Comment by buunguyen** [comment]
Fixed in 5.0

**Comment by buunguyen** [comment]
Sorry I was commenting on the wrong issue. This is not fixed.

**Comment by JoepKockelkorn** [comment]
I can confirm this bug on version 5.0.0. It seems the css selectors for the themes are too generic, or are missing modifiers for the 'open' or 'approved' state of icons. For the Railscasts theme these are some fixes I applied myself using the Stylus extension for the 'open' PR's in the PR overview and the approval icons in a PR:
```css
html.octotree-theme-railscasts svg.open {
  fill: rgb(108, 198, 68);
}

html.octotree-theme-railscasts .TimelineItem-badge.bg-green {
  background-color: rgb(51, 119, 51) !important;
}
```
